-- Quick fix: Create missing RAW tables in Snowflake
-- Run this in Snowflake UI or via snowsql

USE DATABASE RENTS;
USE SCHEMA RAW;

-- Create ApartmentList Raw Table
CREATE TABLE IF NOT EXISTS APTLIST_LONG (
  LOCATION_FIPS_CODE VARCHAR(20),
  REGIONID VARCHAR(50),
  LOCATION_NAME VARCHAR(255),
  LOCATION_TYPE VARCHAR(50),
  STATE VARCHAR(100),
  COUNTY VARCHAR(100),
  METRO VARCHAR(255),
  MONTH DATE,
  RENT_INDEX DECIMAL(10, 2),
  POPULATION INTEGER,
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  S3_FILE_PATH VARCHAR(500)
);

-- Create FRED Raw Table
CREATE TABLE IF NOT EXISTS FRED_CPI_LONG (
  SERIES_ID VARCHAR(50),
  LABEL VARCHAR(500),
  MONTH DATE,
  VALUE DECIMAL(18, 4),
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  S3_FILE_PATH VARCHAR(500)
);

-- Verify tables created
SHOW TABLES IN SCHEMA RAW;

-- Check row counts (should be 0 until we load data)
SELECT 'ZORI_METRO_LONG' as table_name, COUNT(*) as row_count FROM RENTS.RAW.ZORI_METRO_LONG
UNION ALL
SELECT 'APTLIST_LONG', COUNT(*) FROM RENTS.RAW.APTLIST_LONG
UNION ALL
SELECT 'FRED_CPI_LONG', COUNT(*) FROM RENTS.RAW.FRED_CPI_LONG;


